### ISSUE TITLE
卸載

### ISSUE THREAD

**Issue by BrownRhined** [jasoncheng7115/pve-cpatch#2]
"2047171115":["卸載"],
"2047171115":["解除安裝"],

**Comment by jasoncheng7115** [comment]
在原文對應的詞是 "Unmount"，所以使用 "卸載"

**Comment by BrownRhined** [comment]
Un 否定字首
mount安裝

台灣沒有 卸載 這個詞，這是對岸用詞
教育部辭典也沒有卸載這個詞
參照 windows系統語系 或 wmware ESXi 翻譯
zh_TW語系皆沒有卸載這個詞
所以更正為
"2047171115":["解除安裝"],
才是正確的 除非你是用谷哥翻譯，谷歌翻譯目前因為對岸大量提交更正繁體詞彙
目前有混用現象 另外說明一下  對岸的「卸載」 == 台灣的「解除安裝」

**Comment by jasoncheng7115** [comment]
@BrownRhined  您說的對，我剛用微軟語言入口網對照，有幾個詞是我們可以考慮採用的：

mount = 掛接 / 裝載 / 掛載
unmount = 取消掛接 / 取消裝載 / 卸載

所以，看起來 "取消掛接/取消裝載" 是一個不錯的用法，"安裝/解除安裝" 留給 install/uninstall 來使用
